/**
 * PDF Export Utility
 * Generates a professional PDF from the schedule data
 */

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { ScheduleBlock } from '@/components/weekly-schedule-grid'

interface ExportOptions {
  scheduleBlocks: ScheduleBlock[]
  employees: Array<{ id: string; name: string }>
  totalTasks: number
  approvedRecommendations: number
}

/**
 * Export schedule as PDF using html2canvas approach
 */
export async function exportScheduleAsPDF(element: HTMLElement, filename: string = 'schedule.pdf') {
  try {
    // Create canvas from the HTML element
    const canvas = await html2canvas(element, {
      scale: 2, // Higher quality
      logging: false,
      useCORS: true,
      backgroundColor: '#ffffff'
    })

    // Calculate PDF dimensions
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF({
      orientation: 'landscape',
      unit: 'mm',
      format: 'a4'
    })

    const imgWidth = 297 // A4 landscape width in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width

    // Add image to PDF
    pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight)

    // Save the PDF
    pdf.save(filename)
    
    return true
  } catch (error) {
    console.error('Error generating PDF:', error)
    throw error
  }
}

/**
 * Generate a formatted PDF with schedule data
 */
export async function generateSchedulePDF(options: ExportOptions) {
  const { scheduleBlocks, employees, totalTasks, approvedRecommendations } = options
  
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  })

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 15

  // Title
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Weekly Team Schedule', margin, margin + 5)

  // Date
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  const dateStr = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
  pdf.text(`Generated: ${dateStr}`, margin, margin + 12)

  // Summary section
  let yPos = margin + 20
  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Summary', margin, yPos)
  
  yPos += 7
  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Total Tasks: ${totalTasks}`, margin, yPos)
  pdf.text(`Total Employees: ${employees.length}`, margin + 50, yPos)
  pdf.text(`Approved Recommendations: ${approvedRecommendations}`, margin + 110, yPos)

  // Schedule table
  yPos += 15
  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Schedule Details', margin, yPos)

  // Table headers
  yPos += 7
  pdf.setFontSize(9)
  const colWidths = {
    employee: 40,
    task: 45,
    day: 25,
    time: 25,
    duration: 20,
    type: 30
  }
  
  let xPos = margin
  pdf.setFillColor(59, 130, 246) // Blue
  pdf.setTextColor(255, 255, 255)
  pdf.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, 'F')
  
  pdf.text('Employee', xPos, yPos)
  xPos += colWidths.employee
  pdf.text('Task', xPos, yPos)
  xPos += colWidths.task
  pdf.text('Day', xPos, yPos)
  xPos += colWidths.day
  pdf.text('Time', xPos, yPos)
  xPos += colWidths.time
  pdf.text('Duration', xPos, yPos)
  xPos += colWidths.duration
  pdf.text('Type', xPos, yPos)

  // Table rows
  yPos += 6
  pdf.setTextColor(0, 0, 0)
  
  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
  
  scheduleBlocks.forEach((block, index) => {
    if (yPos > pageHeight - 20) {
      pdf.addPage()
      yPos = margin
    }

    const dayName = days[block.day]
    const startHour = Math.floor(block.startTime)
    const startMinute = Math.round((block.startTime - startHour) * 60)
    const timeStr = `${String(startHour).padStart(2, '0')}:${String(startMinute).padStart(2, '0')}`

    xPos = margin
    
    // Alternate row colors
    if (index % 2 === 0) {
      pdf.setFillColor(249, 250, 251)
      pdf.rect(margin, yPos - 4, pageWidth - 2 * margin, 6, 'F')
    }

    pdf.text(block.employeeName.substring(0, 20), xPos, yPos)
    xPos += colWidths.employee
    pdf.text(block.taskName.substring(0, 22), xPos, yPos)
    xPos += colWidths.task
    pdf.text(dayName, xPos, yPos)
    xPos += colWidths.day
    pdf.text(timeStr, xPos, yPos)
    xPos += colWidths.time
    pdf.text(`${block.duration}h`, xPos, yPos)
    xPos += colWidths.duration
    pdf.text(block.type, xPos, yPos)

    yPos += 6
  })

  // Footer
  pdf.setFontSize(8)
  pdf.setTextColor(128, 128, 128)
  pdf.text(
    'Generated by Dynamic Staffing & Scheduling Agent',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  )

  // Save
  const filename = `schedule-${new Date().toISOString().split('T')[0]}.pdf`
  pdf.save(filename)
  
  return filename
}

/**
 * Export the schedule grid as an image-based PDF
 */
export async function exportScheduleGridAsPDF() {
  const scheduleElement = document.querySelector('.weekly-schedule-container') as HTMLElement
  
  if (!scheduleElement) {
    throw new Error('Schedule element not found')
  }

  const filename = `schedule-grid-${new Date().toISOString().split('T')[0]}.pdf`
  await exportScheduleAsPDF(scheduleElement, filename)
  
  return filename
}

